//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesRestaurante : DbContext
    {
        public EntitiesRestaurante()
            : base("name=EntitiesRestaurante")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<INSUMO> INSUMO { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PEDIDO_INSUMO> PEDIDO_INSUMO { get; set; }
        public DbSet<PEDIDO_PLATOS> PEDIDO_PLATOS { get; set; }
        public DbSet<PLATO> PLATO { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<TIPO_PLATO> TIPO_PLATO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
    
        public virtual int INSERTCLIENTE(string p_RUT_CLIENTE, string p_NOMBRE_CLIENTE, string p_APELLIDO_CLIENTE, string p_CORREO, Nullable<decimal> p_TELEFONO)
        {
            var p_RUT_CLIENTEParameter = p_RUT_CLIENTE != null ?
                new ObjectParameter("P_RUT_CLIENTE", p_RUT_CLIENTE) :
                new ObjectParameter("P_RUT_CLIENTE", typeof(string));
    
            var p_NOMBRE_CLIENTEParameter = p_NOMBRE_CLIENTE != null ?
                new ObjectParameter("P_NOMBRE_CLIENTE", p_NOMBRE_CLIENTE) :
                new ObjectParameter("P_NOMBRE_CLIENTE", typeof(string));
    
            var p_APELLIDO_CLIENTEParameter = p_APELLIDO_CLIENTE != null ?
                new ObjectParameter("P_APELLIDO_CLIENTE", p_APELLIDO_CLIENTE) :
                new ObjectParameter("P_APELLIDO_CLIENTE", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTCLIENTE", p_RUT_CLIENTEParameter, p_NOMBRE_CLIENTEParameter, p_APELLIDO_CLIENTEParameter, p_CORREOParameter, p_TELEFONOParameter);
        }
    
        public virtual int INSERTINSUMO(string p_NOMBRE_INSUMO, Nullable<decimal> p_STOCK_INSUMO, string p_UNIDAD_MEDIDA, Nullable<decimal> p_PRECIO, string p_IMGULT)
        {
            var p_NOMBRE_INSUMOParameter = p_NOMBRE_INSUMO != null ?
                new ObjectParameter("P_NOMBRE_INSUMO", p_NOMBRE_INSUMO) :
                new ObjectParameter("P_NOMBRE_INSUMO", typeof(string));
    
            var p_STOCK_INSUMOParameter = p_STOCK_INSUMO.HasValue ?
                new ObjectParameter("P_STOCK_INSUMO", p_STOCK_INSUMO) :
                new ObjectParameter("P_STOCK_INSUMO", typeof(decimal));
    
            var p_UNIDAD_MEDIDAParameter = p_UNIDAD_MEDIDA != null ?
                new ObjectParameter("P_UNIDAD_MEDIDA", p_UNIDAD_MEDIDA) :
                new ObjectParameter("P_UNIDAD_MEDIDA", typeof(string));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_IMGULTParameter = p_IMGULT != null ?
                new ObjectParameter("P_IMGULT", p_IMGULT) :
                new ObjectParameter("P_IMGULT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTINSUMO", p_NOMBRE_INSUMOParameter, p_STOCK_INSUMOParameter, p_UNIDAD_MEDIDAParameter, p_PRECIOParameter, p_IMGULTParameter);
        }
    
        public virtual int INSERTMESA(Nullable<decimal> p_NUM_MESA, Nullable<decimal> p_CANTIDAD_MESA)
        {
            var p_NUM_MESAParameter = p_NUM_MESA.HasValue ?
                new ObjectParameter("P_NUM_MESA", p_NUM_MESA) :
                new ObjectParameter("P_NUM_MESA", typeof(decimal));
    
            var p_CANTIDAD_MESAParameter = p_CANTIDAD_MESA.HasValue ?
                new ObjectParameter("P_CANTIDAD_MESA", p_CANTIDAD_MESA) :
                new ObjectParameter("P_CANTIDAD_MESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTMESA", p_NUM_MESAParameter, p_CANTIDAD_MESAParameter);
        }
    
        public virtual int INSERTPEDIDO(Nullable<decimal> p_ID_CLIENTE, Nullable<decimal> p_NUM_MESA, Nullable<System.DateTime> p_FECHA_PEDIDO)
        {
            var p_ID_CLIENTEParameter = p_ID_CLIENTE.HasValue ?
                new ObjectParameter("P_ID_CLIENTE", p_ID_CLIENTE) :
                new ObjectParameter("P_ID_CLIENTE", typeof(decimal));
    
            var p_NUM_MESAParameter = p_NUM_MESA.HasValue ?
                new ObjectParameter("P_NUM_MESA", p_NUM_MESA) :
                new ObjectParameter("P_NUM_MESA", typeof(decimal));
    
            var p_FECHA_PEDIDOParameter = p_FECHA_PEDIDO.HasValue ?
                new ObjectParameter("P_FECHA_PEDIDO", p_FECHA_PEDIDO) :
                new ObjectParameter("P_FECHA_PEDIDO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPEDIDO", p_ID_CLIENTEParameter, p_NUM_MESAParameter, p_FECHA_PEDIDOParameter);
        }
    
        public virtual int INSERTPEDIDOINSUMO(Nullable<decimal> p_ID_INSUMO, string p_NOMBRE_INSUMO, Nullable<decimal> p_STOCK_INSUMO, string p_UNIDAD_MEDIDA, string p_IMGULT)
        {
            var p_ID_INSUMOParameter = p_ID_INSUMO.HasValue ?
                new ObjectParameter("P_ID_INSUMO", p_ID_INSUMO) :
                new ObjectParameter("P_ID_INSUMO", typeof(decimal));
    
            var p_NOMBRE_INSUMOParameter = p_NOMBRE_INSUMO != null ?
                new ObjectParameter("P_NOMBRE_INSUMO", p_NOMBRE_INSUMO) :
                new ObjectParameter("P_NOMBRE_INSUMO", typeof(string));
    
            var p_STOCK_INSUMOParameter = p_STOCK_INSUMO.HasValue ?
                new ObjectParameter("P_STOCK_INSUMO", p_STOCK_INSUMO) :
                new ObjectParameter("P_STOCK_INSUMO", typeof(decimal));
    
            var p_UNIDAD_MEDIDAParameter = p_UNIDAD_MEDIDA != null ?
                new ObjectParameter("P_UNIDAD_MEDIDA", p_UNIDAD_MEDIDA) :
                new ObjectParameter("P_UNIDAD_MEDIDA", typeof(string));
    
            var p_IMGULTParameter = p_IMGULT != null ?
                new ObjectParameter("P_IMGULT", p_IMGULT) :
                new ObjectParameter("P_IMGULT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPEDIDOINSUMO", p_ID_INSUMOParameter, p_NOMBRE_INSUMOParameter, p_STOCK_INSUMOParameter, p_UNIDAD_MEDIDAParameter, p_IMGULTParameter);
        }
    
        public virtual int INSERTPEDIDOPLATOS(Nullable<decimal> p_ID_PEDIDO, Nullable<decimal> p_ID_PLATO, Nullable<decimal> p_CANTIDAD)
        {
            var p_ID_PEDIDOParameter = p_ID_PEDIDO.HasValue ?
                new ObjectParameter("P_ID_PEDIDO", p_ID_PEDIDO) :
                new ObjectParameter("P_ID_PEDIDO", typeof(decimal));
    
            var p_ID_PLATOParameter = p_ID_PLATO.HasValue ?
                new ObjectParameter("P_ID_PLATO", p_ID_PLATO) :
                new ObjectParameter("P_ID_PLATO", typeof(decimal));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPEDIDOPLATOS", p_ID_PEDIDOParameter, p_ID_PLATOParameter, p_CANTIDADParameter);
        }
    
        public virtual int INSERTPLATO(string p_NOMBRE_PLATO, Nullable<decimal> p_PRECIO_COSTO, Nullable<decimal> p_PRECIO_VENTA, Nullable<decimal> p_TIPO_PLATO, string p_IMG_URL, string p_DESCRIPCION, Nullable<decimal> p_TIEMPO_PREPARACION)
        {
            var p_NOMBRE_PLATOParameter = p_NOMBRE_PLATO != null ?
                new ObjectParameter("P_NOMBRE_PLATO", p_NOMBRE_PLATO) :
                new ObjectParameter("P_NOMBRE_PLATO", typeof(string));
    
            var p_PRECIO_COSTOParameter = p_PRECIO_COSTO.HasValue ?
                new ObjectParameter("P_PRECIO_COSTO", p_PRECIO_COSTO) :
                new ObjectParameter("P_PRECIO_COSTO", typeof(decimal));
    
            var p_PRECIO_VENTAParameter = p_PRECIO_VENTA.HasValue ?
                new ObjectParameter("P_PRECIO_VENTA", p_PRECIO_VENTA) :
                new ObjectParameter("P_PRECIO_VENTA", typeof(decimal));
    
            var p_TIPO_PLATOParameter = p_TIPO_PLATO.HasValue ?
                new ObjectParameter("P_TIPO_PLATO", p_TIPO_PLATO) :
                new ObjectParameter("P_TIPO_PLATO", typeof(decimal));
    
            var p_IMG_URLParameter = p_IMG_URL != null ?
                new ObjectParameter("P_IMG_URL", p_IMG_URL) :
                new ObjectParameter("P_IMG_URL", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_TIEMPO_PREPARACIONParameter = p_TIEMPO_PREPARACION.HasValue ?
                new ObjectParameter("P_TIEMPO_PREPARACION", p_TIEMPO_PREPARACION) :
                new ObjectParameter("P_TIEMPO_PREPARACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTPLATO", p_NOMBRE_PLATOParameter, p_PRECIO_COSTOParameter, p_PRECIO_VENTAParameter, p_TIPO_PLATOParameter, p_IMG_URLParameter, p_DESCRIPCIONParameter, p_TIEMPO_PREPARACIONParameter);
        }
    
        public virtual int INSERTRECETA(Nullable<decimal> p_ID_PLATO, Nullable<decimal> p_ID_INSUMO, Nullable<decimal> p_CANTIDAD_INSUMO)
        {
            var p_ID_PLATOParameter = p_ID_PLATO.HasValue ?
                new ObjectParameter("P_ID_PLATO", p_ID_PLATO) :
                new ObjectParameter("P_ID_PLATO", typeof(decimal));
    
            var p_ID_INSUMOParameter = p_ID_INSUMO.HasValue ?
                new ObjectParameter("P_ID_INSUMO", p_ID_INSUMO) :
                new ObjectParameter("P_ID_INSUMO", typeof(decimal));
    
            var p_CANTIDAD_INSUMOParameter = p_CANTIDAD_INSUMO.HasValue ?
                new ObjectParameter("P_CANTIDAD_INSUMO", p_CANTIDAD_INSUMO) :
                new ObjectParameter("P_CANTIDAD_INSUMO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTRECETA", p_ID_PLATOParameter, p_ID_INSUMOParameter, p_CANTIDAD_INSUMOParameter);
        }
    
        public virtual int INSERTRESERVA(Nullable<decimal> p_ID_CLIENTE, Nullable<decimal> p_NUM_MESA, Nullable<System.DateTime> p_FECHA)
        {
            var p_ID_CLIENTEParameter = p_ID_CLIENTE.HasValue ?
                new ObjectParameter("P_ID_CLIENTE", p_ID_CLIENTE) :
                new ObjectParameter("P_ID_CLIENTE", typeof(decimal));
    
            var p_NUM_MESAParameter = p_NUM_MESA.HasValue ?
                new ObjectParameter("P_NUM_MESA", p_NUM_MESA) :
                new ObjectParameter("P_NUM_MESA", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTRESERVA", p_ID_CLIENTEParameter, p_NUM_MESAParameter, p_FECHAParameter);
        }
    
        public virtual int INSERTROL(string p_NOMBRE_ROL)
        {
            var p_NOMBRE_ROLParameter = p_NOMBRE_ROL != null ?
                new ObjectParameter("P_NOMBRE_ROL", p_NOMBRE_ROL) :
                new ObjectParameter("P_NOMBRE_ROL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTROL", p_NOMBRE_ROLParameter);
        }
    
        public virtual int INSERTUSUARIO(string p_RUT_USUARIO, string p_NOMBRE_USUARIO, string p_APELLIDO_USUARIO, string p_EMAIL_USUARIO, string p_PASSWORD_USUARIO, Nullable<decimal> p_ROL_ID_ROL)
        {
            var p_RUT_USUARIOParameter = p_RUT_USUARIO != null ?
                new ObjectParameter("P_RUT_USUARIO", p_RUT_USUARIO) :
                new ObjectParameter("P_RUT_USUARIO", typeof(string));
    
            var p_NOMBRE_USUARIOParameter = p_NOMBRE_USUARIO != null ?
                new ObjectParameter("P_NOMBRE_USUARIO", p_NOMBRE_USUARIO) :
                new ObjectParameter("P_NOMBRE_USUARIO", typeof(string));
    
            var p_APELLIDO_USUARIOParameter = p_APELLIDO_USUARIO != null ?
                new ObjectParameter("P_APELLIDO_USUARIO", p_APELLIDO_USUARIO) :
                new ObjectParameter("P_APELLIDO_USUARIO", typeof(string));
    
            var p_EMAIL_USUARIOParameter = p_EMAIL_USUARIO != null ?
                new ObjectParameter("P_EMAIL_USUARIO", p_EMAIL_USUARIO) :
                new ObjectParameter("P_EMAIL_USUARIO", typeof(string));
    
            var p_PASSWORD_USUARIOParameter = p_PASSWORD_USUARIO != null ?
                new ObjectParameter("P_PASSWORD_USUARIO", p_PASSWORD_USUARIO) :
                new ObjectParameter("P_PASSWORD_USUARIO", typeof(string));
    
            var p_ROL_ID_ROLParameter = p_ROL_ID_ROL.HasValue ?
                new ObjectParameter("P_ROL_ID_ROL", p_ROL_ID_ROL) :
                new ObjectParameter("P_ROL_ID_ROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTUSUARIO", p_RUT_USUARIOParameter, p_NOMBRE_USUARIOParameter, p_APELLIDO_USUARIOParameter, p_EMAIL_USUARIOParameter, p_PASSWORD_USUARIOParameter, p_ROL_ID_ROLParameter);
        }
    
        public virtual int INSERTVENTA(Nullable<decimal> p_ID_PEDIDO, Nullable<decimal> p_SUB_TOTAL, Nullable<decimal> p_IVA, Nullable<decimal> p_PROPINA, Nullable<decimal> p_TOTAL, Nullable<System.DateTime> p_FECHA, string p_RUT_MESERO, Nullable<decimal> p_TIPOPAGO)
        {
            var p_ID_PEDIDOParameter = p_ID_PEDIDO.HasValue ?
                new ObjectParameter("P_ID_PEDIDO", p_ID_PEDIDO) :
                new ObjectParameter("P_ID_PEDIDO", typeof(decimal));
    
            var p_SUB_TOTALParameter = p_SUB_TOTAL.HasValue ?
                new ObjectParameter("P_SUB_TOTAL", p_SUB_TOTAL) :
                new ObjectParameter("P_SUB_TOTAL", typeof(decimal));
    
            var p_IVAParameter = p_IVA.HasValue ?
                new ObjectParameter("P_IVA", p_IVA) :
                new ObjectParameter("P_IVA", typeof(decimal));
    
            var p_PROPINAParameter = p_PROPINA.HasValue ?
                new ObjectParameter("P_PROPINA", p_PROPINA) :
                new ObjectParameter("P_PROPINA", typeof(decimal));
    
            var p_TOTALParameter = p_TOTAL.HasValue ?
                new ObjectParameter("P_TOTAL", p_TOTAL) :
                new ObjectParameter("P_TOTAL", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_RUT_MESEROParameter = p_RUT_MESERO != null ?
                new ObjectParameter("P_RUT_MESERO", p_RUT_MESERO) :
                new ObjectParameter("P_RUT_MESERO", typeof(string));
    
            var p_TIPOPAGOParameter = p_TIPOPAGO.HasValue ?
                new ObjectParameter("P_TIPOPAGO", p_TIPOPAGO) :
                new ObjectParameter("P_TIPOPAGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTVENTA", p_ID_PEDIDOParameter, p_SUB_TOTALParameter, p_IVAParameter, p_PROPINAParameter, p_TOTALParameter, p_FECHAParameter, p_RUT_MESEROParameter, p_TIPOPAGOParameter);
        }
    }
}
