//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.PEDIDO_PLATOS = new HashSet<PEDIDO_PLATOS>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int ID_PEDIDO { get; set; }
        public int CLIENTE_ID_CLIENTE { get; set; }
        public int MESA_NUM_MESA { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public int ESTADO_PEDIDO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MESA MESA { get; set; }
        public virtual ICollection<PEDIDO_PLATOS> PEDIDO_PLATOS { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
