//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PLATOS
    {
        public int ID_PEDIDO_PLATOS { get; set; }
        public int PEDIDO_ID_PEDIDO { get; set; }
        public int PLATO_ID_PLATO { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PLATO PLATO { get; set; }
    }
}
