//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public int ID_RECETA { get; set; }
        public int PLATO_ID_PLATO { get; set; }
        public int INSUMO_ID_INSUMO { get; set; }
        public int CANTIDAD_UTILIZADO { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual PLATO PLATO { get; set; }
    }
}
