//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public int ROL_ID_ROL { get; set; }
        public string RUT_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDO_USUARIO { get; set; }
        public string EMAIL_USUARIO { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
